name: Deploy to Pages with Secret
on:
  # Runs on pushes targeting the default branch
  push:
    branchs: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permission of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  #single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Replace placeholders with our secret variables
        uses: falnyr/replace-env-vars-action@v1.3.2
        env:
          MEANING_OF_LIFE: ${{secrets.MEANING_OF_LIFE}}
        with:
          filename: index.html
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          # Upload entire repository
          path: "."
      - name: Deploy with GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
